# Generated by Django 5.0.6 on 2024-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='content',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
